[project]
name = "defectdetect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "albumentations>=2.0.8",
    "opencv-python>=4.12.0.88",
    "pip>=25.2",
    "scikit-learn>=1.7.2",
    "tensorboard>=2.20.0",
    "ultralytics>=8.3.216",
    "torch==2.8.0",
    "keyboard>=0.13.5",
]
