[project]
name = "crack-detection-toolset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.6",
    "opencv-contrib-python>=4.11.0.86",
    "opencv-python>=4.11.0.86",
    "pip>=25.1.1",
    "pyinstaller>=6.14.0",
    "scikit-image>=0.25.2",
]
